-- File này được sinh tự động bởi scripts/generate-seed-sql.ts — không chỉnh sửa tay.
-- Chạy sau khi đã chạy supabase/schema.sql.

insert into public.projects
  (title_vi, title_en, location_vi, location_en, year, in_progress, investor, contractor, category, image_url, sort_order)
values
  ('Cung cấp, thi công hệ thống SCADA nhà máy thủy điện Sông Chảy 5', 'Supply and installation of the SCADA system for Song Chay 5 Hydropower Plant', 'Nhà máy thủy điện Sông Chảy 5, huyện Xín Mần, tỉnh Hà Giang', 'Song Chay 5 Hydropower Plant, Xin Man District, Ha Giang Province', 2024, false, 'Công ty CP Thủy điện Sông Chảy 5', 'CÔNG TY CP THỦY ĐIỆN SÔNG CHẢY 5', 'nha-may-dien', '/images/projects/Song chay 5.jpg', 35),
  ('Cung cấp, lắp đặt, cấu hình hệ thống Firewall nhà máy thủy điện Bá Thước', 'Supply, installation and configuration of the Firewall system for Ba Thuoc Hydropower Plant', 'Nhà máy thủy điện Bá Thước, huyện Bá Thước, tỉnh Thanh Hóa', 'Ba Thuoc Hydropower Plant, Ba Thuoc District, Thanh Hoa Province', 2024, false, 'Công ty CP Thủy điện Hoàng Anh Thanh Hóa', 'CÔNG TY CP KỸ THUẬT TỰ ĐỘNG HÓA IOT', 'nha-may-dien', null, 34),
  ('Cung cấp, cấu hình, khôi phục hệ thống SCADA nhà máy thủy điện Nậm Giôn', 'Supply, configuration and recovery of the SCADA system for Nam Gion Hydropower Plant', 'Nhà máy thủy điện Nậm Giôn, huyện Quỳnh Nhai, tỉnh Sơn La', 'Nam Gion Hydropower Plant, Quynh Nhai District, Son La Province', 2024, false, 'Công Ty CP Đầu tư Xây dựng và Thương mại Hà Thao', 'CÔNG TY CP ĐẦU TƯ XÂY DỰNG VÀ THƯƠNG MẠI HÀ THAO', 'nha-may-dien', null, 33),
  ('Cấu hình, thí nghiệm hiệu chỉnh (TNHC) hệ thống SCADA', 'Configuration and commissioning tests of the SCADA system', 'TBA 110kV Nhị Chiểu, thị xã Kinh Môn, tỉnh Hải Dương', 'Nhi Chieu 110kV Substation, Kinh Mon Town, Hai Duong Province', 2024, false, 'Công ty TNHH MTV Điện lực Hải Phòng', 'CÔNG TY TNHH TỔNG HỢP THANH SƠN', 'tram-bien-ap', null, 32),
  ('Cấu hình, TNHC hệ thống SCADA MBA T3 TBA 110kV LG Display', 'Configuration and commissioning tests of the SCADA system for T3 transformer, LG Display 110kV Substation', 'TBA 110kV LG Display, Thành phố Hải Phòng', 'LG Display 110kV Substation, Hai Phong City', 2024, false, 'Công ty TNHH MTV Điện lực Hải Phòng', 'CÔNG TY CP TƯ VẤN VÀ XÂY LẮP AN DƯƠNG', 'tram-bien-ap', null, 31),
  ('Cung cấp và lắp đặt thiết bị công trình cải tạo và nâng công suất (NCS) TBA 110kV SIC Hải Dương', 'Supply and installation of equipment for the renovation and capacity upgrade of SIC Hai Duong 110kV Substation', 'TBA 110kV SIC, thị xã Kinh Môn, tỉnh Hải Dương', 'SIC 110kV Substation, Kinh Mon Town, Hai Duong Province', 2024, false, 'Công ty Cổ phần Tân Hà Kiều', 'CÔNG TY CP ĐẦU TƯ VÀ XÂY LẮP ĐÔNG ĐÔ', 'tram-bien-ap', '/images/projects/SIC_1.jpg', 30),
  ('Cung cấp, lắp đặt, thí nghiệm hiệu chỉnh rơ le F87L TBA 110kV SIC Hải Dương', 'Supply, installation and commissioning tests of the F87L relay at SIC Hai Duong 110kV Substation', 'TBA 110kV SIC, thị xã Kinh Môn, tỉnh Hải Dương', 'SIC 110kV Substation, Kinh Mon Town, Hai Duong Province', 2024, false, 'Công ty Cổ phần Tân Hà Kiều', 'CÔNG TY CP ĐẦU TƯ VÀ XÂY LẮP ĐÔNG ĐÔ', 'tram-bien-ap', '/images/projects/SIC_2.jpg', 29),
  ('Cung cấp, lắp đặt thiết bị phần mềm trạm bơm Vĩnh Trị II, Kinh Thanh II', 'Supply and installation of equipment and software for Vinh Tri II and Kinh Thanh II pumping stations', 'Trạm bơm Vĩnh Trị II, Kinh Thanh II', 'Vinh Tri II and Kinh Thanh II Pumping Stations', 2024, false, 'Công ty TNHH Điện nước Việt Nam', 'CÔNG TY TNHH MTV KHAI THÁC CÔNG TRÌNH THỦY LỢI BẮC NAM HÀ', 'san-xuat-cong-nghiep', '/images/projects/Vinh_Tri_1.png', 28),
  ('Khắc phục, sửa chữa hệ thống SCADA các trạm bơm Hữu Bị, Vĩnh Trị I, Cổ Đam, Nhâm Tràng sau cơn bão số 3', 'Repair and recovery of the SCADA system at Huu Bi, Vinh Tri I, Co Dam and Nham Trang pumping stations after Typhoon No. 3', 'Trạm bơm Hữu Bị, Vĩnh Trị I, Cổ Đam, Nhâm Tràng, tỉnh Nam Định, Hà Nam', 'Huu Bi, Vinh Tri I, Co Dam and Nham Trang Pumping Stations, Nam Dinh and Ha Nam Provinces', 2024, false, 'Công ty TNHH Điện nước Việt Nam', 'CÔNG TY TNHH MTV KHAI THÁC CÔNG TRÌNH THỦY LỢI BẮC NAM HÀ', 'san-xuat-cong-nghiep', '/images/projects/Vinh_Tri_2.jpg', 27),
  ('Cấu hình, thử nghiệm hệ thống SCADA nhà máy điện mặt trời Cát Hiệp', 'Configuration and testing of the SCADA system for Cat Hiep Solar Power Plant', 'Nhà máy điện mặt trời Cát Hiệp, xã Cát Hiệp, tỉnh Bình Định', 'Cat Hiep Solar Power Plant, Cat Hiep Commune, Binh Dinh Province', 2024, false, 'Công ty CP Năng lượng và Công nghệ cao TTP Bình Định', 'CÔNG TY CP NĂNG LƯỢNG VÀ CÔNG NGHỆ CAO TTP BÌNH ĐỊNH', 'dien-mat-troi', null, 26),
  ('Cung cấp, lắp đặt hệ thống SCADA trạm biến áp CTH', 'Supply and installation of the SCADA system for the CTH substation', 'Bến Cảng Tổng Hợp – Container Hòa Phát', 'Hoa Phat General & Container Port', 2024, false, 'Công ty CP Cảng Tổng Hợp Hòa Phát', 'CÔNG TY CỔ PHẦN HAWEE SẢN XUẤT VÀ THƯƠNG MẠI', 'san-xuat-cong-nghiep', null, 25),
  ('Cấu hình, TNHC hệ thống SCADA MBA T2 TBA 110kV Thành Thắng 3', 'Configuration and commissioning tests of the SCADA system for T2 transformer, Thanh Thang 3 110kV Substation', 'Nhà máy xi măng Thành Thắng, huyện Thanh Liêm, tỉnh Hà Nam', 'Thanh Thang Cement Plant, Thanh Liem District, Ha Nam Province', 2024, false, 'Công ty CP Xi măng Thành Thắng', 'CÔNG TY CỔ PHẦN XI MĂNG THÀNH THẮNG', 'san-xuat-cong-nghiep', '/images/projects/Thanh_thang_1.jpg', 24),
  ('Cung cấp, cấu hình hệ thống SCADA cho các trạm nguyên liệu – Khu liên hợp Hòa Phát Dung Quất 2', 'Supply and configuration of the SCADA system for raw-material stations at the Hoa Phat Dung Quat 2 complex', 'Nhà máy Thép Hòa Phát Dung Quất 2', 'Hoa Phat Dung Quat 2 Steel Plant', 2025, false, 'Công ty CP Thép Hòa Phát Dung Quất', 'CÔNG TY TNHH KỸ THUẬT CƠ ĐIỆN E-POWER', 'san-xuat-cong-nghiep', null, 23),
  ('Cung cấp, cấu hình, khôi phục hệ thống SCADA nhà máy thủy điện Nậm Pia', 'Supply, configuration and recovery of the SCADA system for Nam Pia Hydropower Plant', 'Nhà máy thủy điện Nậm Pia, huyện Mường La, tỉnh Sơn La', 'Nam Pia Hydropower Plant, Muong La District, Son La Province', 2025, false, 'Công ty CP Thủy điện Nậm Pia', 'CÔNG TY CỔ PHẦN THỦY ĐIỆN NẬM PIA', 'nha-may-dien', null, 22),
  ('Cung cấp vật tư, lắp đặt, cấu hình, kết nối A1 các thiết bị SCADA', 'Supply of materials, installation, configuration and A1 connection of SCADA equipment', 'Nhà máy xi măng Thành Thắng, huyện Thanh Liêm, tỉnh Hà Nam', 'Thanh Thang Cement Plant, Thanh Liem District, Ha Nam Province', 2025, false, 'Công ty CP Xi măng Thành Thắng', 'CÔNG TY CỔ PHẦN XI MĂNG THÀNH THẮNG', 'san-xuat-cong-nghiep', '/images/projects/Thanh_thang_1.jpg', 21),
  ('Cung cấp card truyền thông và khôi phục kênh truyền về A1 nhà máy thủy điện Chiềng Công 2', 'Supply of communication cards and recovery of the A1 telemetry channel for Chieng Cong 2 Hydropower Plant', 'Nhà máy thủy điện Chiềng Công 2, huyện Mường La, tỉnh Sơn La', 'Chieng Cong 2 Hydropower Plant, Muong La District, Son La Province', 2025, false, 'Công ty CP Xây dựng và Thương mại Lam Sơn', 'CÔNG TY CP XÂY DỰNG VÀ THƯƠNG MẠI LAM SƠN', 'nha-may-dien', null, 20),
  ('Cung cấp, lắp đặt hệ thống thông tin, SCADA; thử nghiệm hệ thống điều tốc, kích từ Nhà máy Thủy điện Nậm Xe 2', 'Supply and installation of the telecom/SCADA systems; testing of the governor and excitation systems for Nam Xe 2 Hydropower Plant', 'Nhà máy thủy điện Nậm Xe, huyện Mường So, tỉnh Lai Châu', 'Nam Xe Hydropower Plant, Muong So District, Lai Chau Province', 2025, false, 'Công ty CP Thủy điện Thành Phát Lai Châu', 'CÔNG TY CP THỦY ĐIỆN THÀNH PHÁT LAI CHÂU', 'nha-may-dien', null, 19),
  ('Cung cấp, thi công hệ thống SCADA nhà máy nhiệt điện Sơn Động', 'Supply and installation of the SCADA system for Son Dong Thermal Power Plant', 'Nhà máy nhiệt điện Sơn Động, huyện Sơn Động, tỉnh Bắc Giang', 'Son Dong Thermal Power Plant, Son Dong District, Bac Giang Province', 2025, false, 'Công ty Nhiệt điện Sơn Động - TKV', 'CÔNG TY NHIỆT ĐIỆN SƠN ĐỘNG - TKV', 'nha-may-dien', null, 18),
  ('Cấu hình, sửa chữa hệ thống tự động điều chỉnh điện áp MBA T1', 'Configuration and repair of the automatic voltage regulation system for transformer T1', 'Trạm biến áp 110kV Quất Động', 'Quat Dong 110kV Substation', 2025, false, 'Công ty CP Tập đoàn Gang thép Hàn Việt', 'CÔNG TY CP TẬP ĐOÀN GANG THÉP HÀN VIỆT', 'tram-bien-ap', null, 17),
  ('Cung cấp, thay thế, khôi phục hệ thống SCADA', 'Supply, replacement and recovery of the SCADA system', 'Cụm nhà máy thủy điện Nậm Chim 2, Xím Vàng 2, Suối Lừm 1, huyện Bắc Yên, tỉnh Sơn La', 'Nam Chim 2, Xim Vang 2 and Suoi Lum 1 Hydropower Cluster, Bac Yen District, Son La Province', 2025, false, 'Công Ty CP Tư vấn Phát triển Năng lượng Tây Bắc', 'CÔNG TY CP TƯ VẤN PHÁT TRIỂN NĂNG LƯỢNG TÂY BẮC', 'nha-may-dien', null, 16),
  ('Cung cấp bộ cảnh báo Taplo', 'Supply of the Taplo alarm annunciator panel', 'TBA 110kV Truông Bành, huyện Quế Phong, tỉnh Nghệ An', 'Truong Banh 110kV Substation, Que Phong District, Nghe An Province', 2025, false, 'Công ty Cổ phần Thủy điện Quế Phong', 'CÔNG TY CỔ PHẦN THỦY ĐIỆN QUẾ PHONG', 'tram-bien-ap', null, 15),
  ('Khôi phục hệ thống kênh truyền về A1', 'Recovery of the A1 telemetry channel', 'TBA 110kV nhà máy xi măng Đại Dương, xã Trường Lâm, tỉnh Thanh Hóa', 'Dai Duong Cement Plant 110kV Substation, Truong Lam Commune, Thanh Hoa Province', 2025, false, 'Công ty Cổ phần Xi măng Đại Dương', 'CÔNG TY CP XI MĂNG ĐẠI DƯƠNG', 'tram-bien-ap', null, 14),
  ('Lắp đặt, cấu hình, kết nối tín hiệu báo cháy với TTĐKX Hà Nội', 'Installation, configuration and connection of the fire-alarm signal to the Hanoi Regional Control Center', 'TBA 110kV Trôi, huyện Hoài Đức, TP. Hà Nội', 'Troi 110kV Substation, Hoai Duc District, Hanoi', 2025, false, 'Công ty TNHH Cơ điện FIS', 'CÔNG TY TNHH CƠ ĐIỆN FIS', 'tram-bien-ap', null, 13),
  ('Cung cấp, lắp đặt, thay thế màn hình HMI', 'Supply, installation and replacement of the HMI display', 'Nhà máy thủy điện Nậm Pia, huyện Mường La, tỉnh Sơn La', 'Nam Pia Hydropower Plant, Muong La District, Son La Province', 2025, false, 'Công ty Cổ phần Thủy điện Nậm Pia', 'CÔNG TY CỔ PHẦN THỦY ĐIỆN NẬM PIA', 'nha-may-dien', null, 12),
  ('Cung cấp, cấu hình, hiệu chỉnh hệ thống thông tin, SCADA', 'Supply, configuration and commissioning of the telecom and SCADA systems', 'Nhà máy thủy điện Hòa Thuận, xã Phục Hòa, tỉnh Cao Bằng', 'Hoa Thuan Hydropower Plant, Phuc Hoa Commune, Cao Bang Province', 2025, false, 'Công ty CP Thủy điện Hòa Thuận', 'CÔNG TY CP DỊCH VỤ KỸ THUẬT ĐIỆN LỰC VIỆT NAM', 'nha-may-dien', null, 11),
  ('Cung cấp, khôi phục hệ thống DCS, kết nối SCADA TBA 110kV NMTĐ Nậm Công về Trung tâm Điều độ miền Bắc (NSO)', 'Supply and recovery of the DCS system; SCADA connection from Nam Cong Hydropower Plant substation to the Northern Load Dispatch Center (NSO)', 'Nhà máy thủy điện Nậm Công, xã Sông Mã, tỉnh Sơn La', 'Nam Cong Hydropower Plant, Song Ma Commune, Son La Province', 2025, false, 'Công ty CP Đầu tư và Phát triển Điện Tây Bắc', 'CÔNG TY CP ĐẦU TƯ VÀ PHÁT TRIỂN ĐIỆN TÂY BẮC', 'nha-may-dien', null, 10),
  ('Cung cấp, cấu hình, khôi phục hệ thống SCADA nhà máy thủy điện Xuân Minh', 'Supply, configuration and recovery of the SCADA system for Xuan Minh Hydropower Plant', 'Nhà máy thủy điện Xuân Minh, xã Thường Xuân, tỉnh Thanh Hóa', 'Xuan Minh Hydropower Plant, Thuong Xuan Commune, Thanh Hoa Province', 2025, false, 'Công ty CP Thủy điện Xuân Minh', 'CÔNG TY CP THỦY ĐIỆN XUÂN MINH', 'nha-may-dien', null, 9),
  ('Khôi phục hệ thống thông tin, SCADA nhà máy thủy điện Suối Chăn 2', 'Recovery of the telecom and SCADA systems for Suoi Chan 2 Hydropower Plant', 'Nhà máy thủy điện Suối Chăn 2, huyện Văn Bàn, tỉnh Lào Cai', 'Suoi Chan 2 Hydropower Plant, Van Ban District, Lao Cai Province', 2025, false, 'Công ty CP Đầu tư Năng lượng VIDIFI', 'CÔNG TY CP ĐẦU TƯ NĂNG LƯỢNG VIDIFI', 'nha-may-dien', null, 8),
  ('Cấu hình, khôi phục hệ thống SCADA nhà máy thủy điện Thanh Thủy 1', 'Configuration and recovery of the SCADA system for Thanh Thuy 1 Hydropower Plant', 'Nhà máy thủy điện Thanh Thủy 1, huyện Vị Xuyên, tỉnh Hà Giang', 'Thanh Thuy 1 Hydropower Plant, Vi Xuyen District, Ha Giang Province', 2025, false, 'Công ty CP Thủy điện Thanh Thủy', 'CÔNG TY CP THỦY ĐIỆN THANH THỦY', 'nha-may-dien', null, 7),
  ('Thay thế, cấu hình PLC tại tủ LCU2 nhà máy thủy điện Chiềng Công 2', 'Replacement and configuration of the PLC in the LCU2 cabinet at Chieng Cong 2 Hydropower Plant', 'Nhà máy thủy điện Chiềng Công 2, huyện Mường La, tỉnh Sơn La', 'Chieng Cong 2 Hydropower Plant, Muong La District, Son La Province', 2025, false, 'Công ty CP Xây dựng và Thương mại Lam Sơn', 'CÔNG TY CP XÂY DỰNG VÀ THƯƠNG MẠI LAM SƠN', 'nha-may-dien', null, 6),
  ('Lắp đặt tụ bù tại thanh cái trung áp các TBA 110kV Nam Sách, TBA 110kV HP96 Đồ Sơn, TBA 110kV Việt Ý, TP Hải Phòng', 'Installation of medium-voltage busbar capacitor banks at Nam Sach, HP96 Do Son and Viet Y 110kV Substations, Hai Phong City', 'TBA 110kV Nam Sách, HP96 Đồ Sơn, Việt Ý, Thành phố Hải Phòng', 'Nam Sach, HP96 Do Son and Viet Y 110kV Substations, Hai Phong City', 2026, true, 'Công ty Cổ phần Công nghiệp Đại Dương', 'CÔNG TY ĐIỆN LỰC HẢI PHÒNG', 'tram-bien-ap', '/images/projects/tu_bu.jpg', 5),
  ('Cung cấp, lắp đặt vật tư thiết bị (VTTB) và cung cấp dịch vụ cho ngăn đường dây 173 tại TBA 110kV Thuận Châu', 'Supply and installation of materials/equipment and services for line bay 173 at Thuan Chau 110kV Substation', 'TBA 110kV Thuận Châu, tỉnh Sơn La', 'Thuan Chau 110kV Substation, Son La Province', 2026, true, 'Công ty CP Đầu tư Xây dựng và Thương mại Hà Thao', 'CÔNG TY CP ĐẦU TƯ XÂY DỰNG VÀ THƯƠNG MẠI HÀ THAO', 'tram-bien-ap', '/images/projects/Thuan_Chau_1.jpg', 4),
  ('Cung cấp, lắp đặt hệ thống thông tin, SCADA; thử nghiệm hệ thống điều tốc, kích từ Nhà máy Thủy điện Nậm Xe 2', 'Supply and installation of the telecom/SCADA systems; testing of the governor and excitation systems for Nam Xe 2 Hydropower Plant', 'Nhà máy thủy điện Nậm Xe, huyện Mường So, tỉnh Lai Châu', 'Nam Xe Hydropower Plant, Muong So District, Lai Chau Province', 2026, true, 'Công ty CP Thủy điện Thành Phát Lai Châu', 'CÔNG TY CP THỦY ĐIỆN THÀNH PHÁT LAI CHÂU', 'nha-may-dien', null, 3),
  ('Cung cấp vật tư, dịch vụ cho tủ FRTU – Khu công nghiệp Kim Thành', 'Supply of materials and services for the FRTU cabinet – Kim Thanh Industrial Park', 'Khu công nghiệp Kim Thành, Hải Phòng', 'Kim Thanh Industrial Park, Hai Phong', 2026, true, 'Công ty TNHH Điện lực Bắc Việt Nam', 'CÔNG TY TNHH ĐIỆN LỰC BẮC VIỆT NAM', 'tram-bien-ap', null, 2),
  ('Cung cấp, lắp đặt thiết bị, dịch vụ kỹ thuật thuộc dự án thay thế rơ le F87L NMTĐ Trạm Tấu – tỉnh Lào Cai', 'Supply and installation of equipment and technical services for the F87L relay replacement project at Tram Tau Hydropower Plant, Lao Cai Province', 'Nhà máy thủy điện Trạm Tấu, tỉnh Lào Cai', 'Tram Tau Hydropower Plant, Lao Cai Province', 2026, true, 'Công ty CP Thủy điện Trạm Tấu', 'CÔNG TY CP THỦY ĐIỆN TRẠM TẤU', 'nha-may-dien', null, 1);

insert into public.partners (name, logo_url, sort_order)
values
  ('Phoenix Contact', '/images/partners/phoenix-contact.svg', 1),
  ('Siemens', '/images/partners/siemens.svg', 2),
  ('Mitsubishi Electric', '/images/partners/mitsubishi.svg', 3),
  ('ABB', '/images/partners/abb.svg', 4),
  ('Sick', '/images/partners/sick.svg', 5),
  ('Taikai', '/images/partners/taikai.svg', 6),
  ('Chint', '/images/partners/chint.svg', 7);

insert into public.posts (slug, title_vi, title_en, excerpt_vi, excerpt_en, content_vi, content_en, cover_image, category, status, published_at)
values
  ('he-thong-scada-nha-may-thuy-dien-song-chay-5', 'DTCA cung cấp, thi công hệ thống SCADA Nhà máy thủy điện Sông Chảy 5', 'DTCA delivers the SCADA system for Song Chay 5 Hydropower Plant', 'Năm 2024, DTCA đã triển khai cung cấp và thi công trọn gói hệ thống SCADA cho Nhà máy thủy điện Sông Chảy 5 tại huyện Xín Mần, tỉnh Hà Giang, đảm bảo tiến độ và tiêu chí an toàn - chất lượng.', 'In 2024, DTCA delivered and installed a turnkey SCADA system for Song Chay 5 Hydropower Plant in Xin Man District, Ha Giang Province, meeting all safety and quality requirements on schedule.', 'Nhà máy thủy điện Sông Chảy 5 là một trong những dự án tiêu biểu mà DTCA đã đồng hành cùng Công ty CP Thủy điện Sông Chảy 5 trong năm 2024.

Đội ngũ kỹ sư tự động hóa và hệ thống điện của DTCA đã thực hiện khảo sát, thiết kế và thi công hệ thống SCADA giám sát - điều khiển toàn bộ quá trình vận hành của nhà máy, giúp đơn vị vận hành theo dõi thông số kỹ thuật theo thời gian thực và xử lý sự cố nhanh chóng.

Dự án được hoàn thành đúng tiến độ, đáp ứng tiêu chí "AN TOÀN - TIẾN ĐỘ - HIỆU QUẢ - CHẤT LƯỢNG" mà DTCA luôn theo đuổi trong mọi công trình.', 'Song Chay 5 Hydropower Plant is one of the flagship projects DTCA carried out together with Song Chay 5 Hydropower JSC in 2024.

DTCA''s automation and power-system engineers conducted the survey, design and installation of a SCADA system to monitor and control the plant''s entire operation, allowing the operator to track real-time parameters and respond quickly to incidents.

The project was completed on schedule, in line with DTCA''s guiding principle of "SAFETY - SCHEDULE - EFFICIENCY - QUALITY" on every project.', '/images/placeholder-industrial.svg', 'nha-may-dien', 'published', '2024-11-15'),
  ('scada-tram-nguyen-lieu-hoa-phat-dung-quat-2', 'Cung cấp, cấu hình hệ thống SCADA cho các trạm nguyên liệu Khu liên hợp Hòa Phát Dung Quất 2', 'SCADA system for raw-material stations at the Hoa Phat Dung Quat 2 complex', 'Năm 2025, DTCA tiếp tục mở rộng hoạt động sang lĩnh vực sản xuất công nghiệp quy mô lớn với dự án cung cấp, cấu hình hệ thống SCADA cho các trạm nguyên liệu tại Nhà máy Thép Hòa Phát Dung Quất 2.', 'In 2025, DTCA expanded into large-scale industrial manufacturing with a project supplying and configuring the SCADA system for raw-material stations at the Hoa Phat Dung Quat 2 Steel Plant.', 'Hợp tác cùng Công ty TNHH Kỹ thuật Cơ điện E-Power, DTCA đảm nhận phần cung cấp và cấu hình hệ thống SCADA cho các trạm nguyên liệu thuộc Khu liên hợp Hòa Phát Dung Quất 2.

Đây là dự án có quy mô kỹ thuật phức tạp, đòi hỏi khả năng tích hợp dữ liệu từ nhiều trạm nguyên liệu về một trung tâm giám sát chung, giúp chủ đầu tư tối ưu hóa vận hành dây chuyền sản xuất thép.

Thành công của dự án là minh chứng cho năng lực của DTCA không chỉ trong lĩnh vực năng lượng mà còn ở các ngành sản xuất công nghiệp nặng.', 'Working with E-Power Mechanical & Electrical Engineering Co., Ltd., DTCA was responsible for supplying and configuring the SCADA system for the raw-material stations within the Hoa Phat Dung Quat 2 complex.

This technically complex project required integrating data from multiple raw-material stations into a single monitoring center, helping the investor optimize the steel production line.

The project''s success demonstrates DTCA''s capability beyond the energy sector, extending into heavy industrial manufacturing.', '/images/placeholder-industrial.svg', 'san-xuat-cong-nghiep', 'published', '2025-04-08'),
  ('dtca-giai-phap-tu-dong-hoa-toan-dien', 'DTCA – Giải pháp tự động hóa, SCADA và thiết bị điện toàn diện cho ngành điện', 'DTCA – Comprehensive automation, SCADA and electrical-equipment solutions for the power industry', 'Với đội ngũ 24 kỹ sư giàu kinh nghiệm, DTCA cung cấp trọn gói giải pháp tự động hóa SCADA/DCS, hệ thống thông tin và thiết bị nhất thứ, tủ điều khiển bảo vệ cho các nhà máy điện, trạm biến áp và khu công nghiệp.', 'With a team of 24 experienced engineers, DTCA provides end-to-end automation SCADA/DCS solutions, information systems and primary equipment/protection-control cabinets for power plants, substations and industrial parks.', 'CÔNG TY TNHH THƯƠNG MẠI VÀ KỸ THUẬT DTCA được thành lập bởi các kỹ sư giàu kinh nghiệm trong lĩnh vực tự động hóa, hệ thống thông tin và hệ thống điện.

DTCA hợp tác với các đối tác uy tín hàng đầu trong và ngoài nước về thiết bị điện, tự động hóa như Phoenix Contact, Siemens, Mitsubishi, ABB, Sick, Taikai, Chint... để mang lại giải pháp tự động hóa tin cậy và an toàn nhất cho khách hàng.

Ba nhóm dịch vụ cốt lõi của DTCA gồm: (1) Giải pháp tự động hóa SCADA/DCS, (2) Hệ thống thông tin (switch, firewall, router), (3) Thiết bị nhất thứ và tủ điều khiển, bảo vệ 220kV/110kV.

DTCA luôn hoạt động theo tiêu chí "AN TOÀN - TIẾN ĐỘ - HIỆU QUẢ - CHẤT LƯỢNG", hướng tới sự hài lòng tuyệt đối của khách hàng trong từng công trình, dự án.', 'DTCA Trading and Technical Company Limited was founded by experienced engineers in automation, information systems and power systems.

DTCA partners with leading domestic and international brands in electrical equipment and automation such as Phoenix Contact, Siemens, Mitsubishi, ABB, Sick, Taikai and Chint to deliver the most reliable and safe automation solutions to customers.

DTCA''s three core service groups are: (1) SCADA/DCS automation solutions, (2) Information systems (switches, firewalls, routers), and (3) Primary equipment and 220kV/110kV protection-control cabinets.

DTCA operates under the principle of "SAFETY - SCHEDULE - EFFICIENCY - QUALITY", aiming for complete customer satisfaction on every project.', '/images/hero-industrial.svg', 'cong-nghe', 'published', '2026-01-10');
